<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../api'
import { saveCreatedPoll } from '../utils/storage'

const router=useRouter(),title=ref(''),questions=ref([{text:'',options:['',''],multiple:false}]),resultsVisible=ref(true),busy=ref(false),error=ref('')
function addQuestion(){questions.value.push({text:'',options:['',''],multiple:false})}
function removeQuestion(i){if(questions.value.length>1)questions.value.splice(i,1)}
function addOption(question){if(question.options.length<8)question.options.push('')}
function removeOption(question,i){if(question.options.length>2)question.options.splice(i,1)}
async function submit(){error.value='';const payload={title:title.value.trim(),results_visible:resultsVisible.value,questions:questions.value.map(q=>({text:q.text.trim(),options:q.options.map(v=>v.trim()).filter(Boolean),multiple:q.multiple}))};if(!payload.title||payload.questions.some(q=>!q.text||q.options.length<2)){error.value='Введите название, каждый вопрос и минимум два варианта ответа';return}busy.value=true;try{const poll=await api.createPoll(payload);saveCreatedPoll({id:poll.id,title:payload.title,adminToken:poll.admin_token,publicLink:poll.public_link,adminLink:poll.admin_link});router.push({path:`/poll/${poll.id}/results`,query:{created:'1'}})}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template><section class="mx-auto max-w-2xl px-5 pb-16 pt-10 sm:px-8 sm:pt-20"><RouterLink to="/" class="text-sm font-bold text-ink/50 hover:text-coral">← На главную</RouterLink><h1 class="mt-10 font-display text-5xl sm:text-6xl">Новый опрос</h1><form class="mt-10 space-y-8" @submit.prevent="submit"><label class="block"><span class="label">Название</span><input v-model="title" class="field mt-2 text-lg" placeholder="Например, летние планы" autofocus></label><fieldset v-for="(question,i) in questions" :key="i" class="rounded-3xl border border-ink/10 bg-white/40 p-5 sm:p-7"><legend class="label">Вопрос {{i+1}}</legend><input v-model="question.text" class="field mt-2 text-lg" placeholder="Куда поедем летом?"><label class="mt-5 flex cursor-pointer items-center gap-3 text-sm font-bold"><input v-model="question.multiple" type="checkbox" class="h-5 w-5 accent-coral"><span>Можно выбрать несколько вариантов</span></label><div class="mt-5"><span class="label">Варианты ответа</span><div v-for="(_,j) in question.options" :key="j" class="mt-3 flex gap-2"><input v-model="question.options[j]" class="field" :aria-label="`Вопрос ${i+1}, вариант ${j+1}`" :placeholder="`Вариант ${j+1}`"><button v-if="question.options.length>2" type="button" class="px-3 text-xl text-ink/35 hover:text-coral" :aria-label="`Удалить вариант ${j+1}`" @click="removeOption(question,j)">×</button></div><button type="button" class="mt-4 text-sm font-bold text-coral" @click="addOption(question)">+ Добавить вариант</button></div><button v-if="questions.length>1" type="button" class="mt-5 text-sm font-bold text-ink/45 hover:text-coral" @click="removeQuestion(i)">Удалить вопрос</button></fieldset><button type="button" class="button button-light w-full sm:w-auto" @click="addQuestion">+ Добавить вопрос</button><label class="flex cursor-pointer items-start gap-3 rounded-3xl border border-ink/10 bg-white/40 p-5 text-sm font-bold sm:p-7"><input v-model="resultsVisible" type="checkbox" class="mt-0.5 h-5 w-5 accent-coral"><span>Показывать результаты</span></label><p v-if="error" class="text-sm font-semibold text-coral" role="alert">{{error}}</p><button class="button button-dark w-full" :disabled="busy">{{busy?'Создаём…':'Создать опрос ↗'}}</button></form></section></template>
